import { join } from 'path';
import { ensureRepo, fetchPRHead, createWorktree, removeWorktree, checkoutBranch } from './clone-manager.js';
import { autofixBranchName, createBranch, commitAndPush, commitChanges } from './branch-manager.js';
import { runClaudeFix, runClaudeCIFix } from './fix-runner.js';
import { createAutofixPR } from './pr-creator.js';
import { createAutofixJob, updateAutofixJob, getLatestReview } from '../state/models.js';
import { run } from '../utils/process.js';
import { logger } from '../utils/logger.js';
import type { PRWithReview } from '../state/models.js';
import type { ConfigOutput } from '../config/schema.js';

export interface AutofixResult {
  followUpPrUrl: string | null;
  branchName: string;
}

/** Unique path for a fix worktree, isolated per session. */
function worktreePath(config: ConfigOutput, owner: string, repo: string): string {
  return join(config.workDir, owner, `${repo}.worktrees`, `fix-${Date.now()}`);
}

export async function runCIJobFix(
  prId: number,
  jobName: string,
  config: ConfigOutput,
  onLog?: (line: string) => void,
): Promise<AutofixResult> {
  const { listOpenPRs } = await import('../state/models.js');
  const prRow = listOpenPRs().find((p) => p.id === prId);
  if (!prRow) throw new Error('PR not found');

  const review = getLatestReview(prId);
  const job = createAutofixJob({ pr_id: prId, review_id: review?.id });

  const repoDir = await ensureRepo(config.workDir, prRow.owner, prRow.repo);
  await fetchPRHead(repoDir, prRow.number, prRow.head_sha);

  // Each fix gets its own worktree — no conflict with other concurrent fixes
  const wtPath = worktreePath(config, prRow.owner, prRow.repo);
  await createWorktree(repoDir, wtPath, prRow.head_sha);

  try {
    updateAutofixJob(job.id, { status: 'cloning' });

    const tempBranch = `_sk-ci-fix-${Date.now()}`;
    await createBranch(wtPath, tempBranch);
    updateAutofixJob(job.id, { status: 'running', branch: tempBranch });

    await runClaudeCIFix(wtPath, jobName, {
      model: config.reviewModel,
      maxBudgetUsd: config.maxFixCostUsd,
      onLog,
    });

    updateAutofixJob(job.id, { status: 'pushing' });
    const committed = await commitChanges(wtPath,
      `ci-fix: fix ${jobName} failure on PR #${prRow.number}`);
    if (!committed) throw new Error('CI fix made no changes to commit');

    const { getPRHeadInfo, getOctokit } = await import('../github/client.js');
    const { headBranch, isFork } = await getPRHeadInfo(prRow.owner, prRow.repo, prRow.number);

    if (!isFork) {
      const push = await run('git', ['-C', wtPath, 'push', 'origin', `${tempBranch}:${headBranch}`]);
      if (push.exitCode !== 0) {
        throw new Error(`Failed to push fix to branch ${headBranch}: ${push.stderr.slice(0, 200)}`);
      }
      updateAutofixJob(job.id, { status: 'done' });
      logger.info({ prId, jobName, headBranch }, 'CI fix pushed to PR branch');
      return { followUpPrUrl: null, branchName: headBranch };
    }

    // Fork PR — create a follow-up PR targeting the same base
    const fixBranch = `ci-fix/pr-${prRow.number}-${jobName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${Date.now()}`;
    await run('git', ['-C', wtPath, 'branch', '-m', tempBranch, fixBranch]);
    const push = await run('git', ['-C', wtPath, 'push', 'origin', fixBranch]);
    if (push.exitCode !== 0) throw new Error(`git push failed: ${push.stderr.slice(0, 200)}`);

    const body = [
      `Fixes CI job failure: **${jobName}** on PR #${prRow.number} (fork PR — cannot push directly).`,
      '',
      `**Original PR**: #${prRow.number} — ${prRow.title}`,
      `**Based on**: commit \`${prRow.head_sha.slice(0, 7)}\``,
      '',
      '---',
      '*Generated by [signal-keeper](https://github.com/platinummonkey/signal-keeper) CI fix*',
    ].join('\n');
    const { data } = await getOctokit().pulls.create({
      owner: prRow.owner, repo: prRow.repo,
      title: `ci-fix: ${jobName} (PR #${prRow.number})`,
      head: fixBranch, base: prRow.base_branch, body,
    });

    updateAutofixJob(job.id, { status: 'done', follow_up_pr_url: data.html_url });
    logger.info({ prId, jobName, url: data.html_url }, 'CI fix follow-up PR created (fork)');
    return { followUpPrUrl: data.html_url, branchName: fixBranch };

  } catch (err) {
    updateAutofixJob(job.id, { status: 'failed', error: (err as Error).message });
    throw err;
  } finally {
    await removeWorktree(repoDir, wtPath);
  }
}

export async function runAutofix(pr: PRWithReview, config: ConfigOutput, onLog?: (line: string) => void): Promise<AutofixResult> {
  const review = getLatestReview(pr.id);
  if (!review) throw new Error('No review found for this PR — run a review first');

  const job = createAutofixJob({ pr_id: pr.id, review_id: review.id });

  const repoDir = await ensureRepo(config.workDir, pr.owner, pr.repo);

  // Fetch the base branch tip so we can create a worktree from it
  await run('git', ['-C', repoDir, 'fetch', 'origin', pr.base_branch]);
  const baseSha = (await run('git', ['-C', repoDir, 'rev-parse', `origin/${pr.base_branch}`])).stdout.trim();

  const wtPath = worktreePath(config, pr.owner, pr.repo);
  await createWorktree(repoDir, wtPath, baseSha);

  try {
    updateAutofixJob(job.id, { status: 'cloning' });

    const branchName = autofixBranchName(pr.owner, pr.repo, pr.number);
    await createBranch(wtPath, branchName);
    updateAutofixJob(job.id, { status: 'running', branch: branchName });

    await runClaudeFix(wtPath, review, {
      model: config.reviewModel,
      maxBudgetUsd: config.maxFixCostUsd,
      onLog,
    });

    updateAutofixJob(job.id, { status: 'pushing' });
    await commitAndPush(wtPath, branchName, pr.number);

    const followUpPrUrl = await createAutofixPR({
      owner: pr.owner, repo: pr.repo,
      sourcePrNumber: pr.number, sourcePrTitle: pr.title,
      branchName, baseBranch: pr.base_branch, review,
    });

    updateAutofixJob(job.id, { status: 'done', follow_up_pr_url: followUpPrUrl });
    logger.info({ prNumber: pr.number, followUpPrUrl }, 'Autofix complete');
    return { followUpPrUrl, branchName };

  } catch (err) {
    updateAutofixJob(job.id, { status: 'failed', error: (err as Error).message });
    throw err;
  } finally {
    await removeWorktree(repoDir, wtPath);
  }
}
