import { ensureRepo, checkoutBranch, checkoutPRHead } from './clone-manager.js';
import { autofixBranchName, createBranch, commitAndPush } from './branch-manager.js';
import { runClaudeFix, runClaudeCIFix } from './fix-runner.js';
import { createAutofixPR } from './pr-creator.js';
import { createAutofixJob, updateAutofixJob, getLatestReview } from '../state/models.js';
import { logger } from '../utils/logger.js';
import type { PRWithReview } from '../state/models.js';
import type { ConfigOutput } from '../config/schema.js';

export interface AutofixResult {
  followUpPrUrl: string | null;
  branchName: string;
}

export async function runCIJobFix(
  prId: number,
  jobName: string,
  config: ConfigOutput,
  onLog?: (line: string) => void,
): Promise<AutofixResult> {
  const { listOpenPRs } = await import('../state/models.js');
  const prRow = listOpenPRs().find((p) => p.id === prId);
  if (!prRow) throw new Error('PR not found');

  const review = getLatestReview(prId);
  const sessionId = review?.session_id ?? undefined;

  const job = createAutofixJob({ pr_id: prId, review_id: review?.id });

  try {
    updateAutofixJob(job.id, { status: 'cloning' });
    const repoDir = await ensureRepo(config.workDir, prRow.owner, prRow.repo);
    // Check out the PR's HEAD (not the base branch) so Claude sees the PR's
    // actual changes and can fix the CI failure in context.
    await checkoutPRHead(repoDir, prRow.number, prRow.head_sha);

    const branchName = `ci-fix/pr-${prRow.number}-${jobName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${Date.now()}`;
    await createBranch(repoDir, branchName);
    updateAutofixJob(job.id, { status: 'running', branch: branchName });

    await runClaudeCIFix(repoDir, jobName, {
      model: config.reviewModel,
      maxBudgetUsd: config.maxReviewCostUsd * 2,
      resumeSessionId: sessionId,
      onLog,
    });

    updateAutofixJob(job.id, { status: 'pushing' });
    await commitAndPush(repoDir, branchName, prRow.number);

    const { getOctokit } = await import('../github/client.js');
    const body = [
      `Fixes CI job failure: **${jobName}** on PR #${prRow.number}.`,
      '',
      `**Original PR**: #${prRow.number} — ${prRow.title}`,
      `**Based on**: commit \`${prRow.head_sha.slice(0, 7)}\` (the PR head) so all original changes are included.`,
      '',
      '---',
      '*Generated by signal-keeper CI fix*',
    ].join('\n');
    const { data } = await getOctokit().pulls.create({
      owner: prRow.owner,
      repo: prRow.repo,
      title: `ci-fix: ${jobName} (PR #${prRow.number})`,
      head: branchName,
      base: prRow.base_branch,
      body,
    });

    updateAutofixJob(job.id, { status: 'done', follow_up_pr_url: data.html_url });
    logger.info({ prId, jobName, url: data.html_url }, 'CI job fix complete');

    return { followUpPrUrl: data.html_url, branchName };
  } catch (err) {
    updateAutofixJob(job.id, { status: 'failed', error: (err as Error).message });
    throw err;
  }
}

export async function runAutofix(pr: PRWithReview, config: ConfigOutput): Promise<AutofixResult> {
  const review = getLatestReview(pr.id);
  if (!review) {
    throw new Error('No review found for this PR — run a review first');
  }

  const job = createAutofixJob({ pr_id: pr.id, review_id: review.id });

  try {
    updateAutofixJob(job.id, { status: 'cloning' });
    const repoDir = await ensureRepo(config.workDir, pr.owner, pr.repo);
    await checkoutBranch(repoDir, pr.base_branch);

    const branchName = autofixBranchName(pr.owner, pr.repo, pr.number);
    await createBranch(repoDir, branchName);
    updateAutofixJob(job.id, { status: 'running', branch: branchName });

    await runClaudeFix(repoDir, review, {
      model: config.reviewModel,
      maxBudgetUsd: config.maxReviewCostUsd * 2,
    });

    updateAutofixJob(job.id, { status: 'pushing' });
    await commitAndPush(repoDir, branchName, pr.number);

    const followUpPrUrl = await createAutofixPR({
      owner: pr.owner,
      repo: pr.repo,
      sourcePrNumber: pr.number,
      sourcePrTitle: pr.title,
      branchName,
      baseBranch: pr.base_branch,
      review,
    });

    updateAutofixJob(job.id, { status: 'done', follow_up_pr_url: followUpPrUrl });
    logger.info({ prNumber: pr.number, followUpPrUrl }, 'Autofix complete');

    return { followUpPrUrl, branchName };
  } catch (err) {
    const message = (err as Error).message;
    updateAutofixJob(job.id, { status: 'failed', error: message });
    throw err;
  }
}
