import { getOctokit } from '../github/client.js';
import { logger } from '../utils/logger.js';
import type { Review } from '../state/models.js';

export async function createAutofixPR(opts: {
  owner: string;
  repo: string;
  sourcePrNumber: number;
  sourcePrTitle: string;
  branchName: string;
  baseBranch: string;
  review: Review;
}): Promise<string> {
  const { owner, repo, sourcePrNumber, sourcePrTitle, branchName, baseBranch, review } = opts;

  const body = [
    `This PR applies AI-suggested fixes from the review of #${sourcePrNumber}.`,
    '',
    `**Original PR**: #${sourcePrNumber} — ${sourcePrTitle}`,
    `**Review category**: \`${review.category}\``,
    '',
    '## Changes applied',
    ...review.suggested_changes.map((sc) => `- **${sc.file}**: ${sc.description}`),
    '',
    '## Review notes',
    ...review.notes.map((n) => `- ${n}`),
    '',
    '---',
    '*Generated by signal-keeper autofix*',
  ].join('\n');

  const { data } = await getOctokit().pulls.create({
    owner,
    repo,
    title: `autofix: ${sourcePrTitle} (#${sourcePrNumber})`,
    head: branchName,
    base: baseBranch,
    body,
  });

  logger.info({ owner, repo, prNumber: data.number, url: data.html_url }, 'Created autofix PR');
  return data.html_url;
}
